### ISSUE TITLE
user can scan qrcode

### ISSUE THREAD

**Issue by imufiii** [imufiii/Capstone-INFO6134#12]
User can Scan QR code to Buy tickets , see the figures of upcoming matches

**Comment by mtrigo-fol** [comment]
The vendor's QR code works with your phone (browser) without your app. This is not really a feature. Replace

**Comment by imufiii** [comment]
I canceled this feature because it doesn't provide any significant advantage to the app, as most phones come with built-in camera apps that can scan QR codes
