### ISSUE TITLE
⁠⁠user can organize, group, filter or sort the teams they have chosen

### ISSUE THREAD

**Issue by imufiii** [imufiii/Capstone-INFO6134#8]

**Comment by mtrigo-fol** [comment]
This really should be part of https://github.com/imufiii/Capstone-INFO6134/issues/9 Combined this feature it.

Then you can add a "Users can delete all user data in the settings" feature to Sprint 3, and move either "Dark Mode" or "Languages" to Sprint 2

**Comment by mtrigo-fol** [comment]
Maybe replace this with a "Delete all user data" feature in the settings.

**Comment by ProgrammerShahryar** [comment]
I am delaying this task as I need to create the functionality for all the methods to work correctly which will take some time

**Comment by ProgrammerShahryar** [comment]
I am canceling this task because our app currently is having one favourite team and therefore does not need sorting, organizing, or filtering.

**Comment by ProgrammerShahryar** [comment]
I am canceling this task because our app currently is having one favourite team and therefore does not need sorting, organizing, or filtering.
